services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  webshopv3:
    image: webshopv3
    build:
      context: WebShopV3
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ComputerShopDbV1;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60
      - Yookassa__ShopId=1214467
      - Yookassa__SecretKey=test_Pq3cYBpb6eXypEpy5R1EgaBAml75YPTp68TYP23MJKI
      - Yookassa__BaseUrl=https://api.yookassa.ru/v3/
    depends_on:
      - sqlserver
    restart: unless-stopped

volumes:
  sqlserver_data: